# Site settings
title: Juan Blanco
description: Sharing my notes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juan.blanco.ws" # the base hostname & protocol for your site
twitter_username: juanfranblanco
github_username:  juanfranblanco
google_analytics: UA-66820700-1
disqus_shortname: juanblancows

# Build settings
markdown: redcarpet
highlighter: rouge
permalink: /:title/

gems:
  - jekyll-sitemap
